### ISSUE TITLE
Explanation of variables for `flux-web-frontend`

### ISSUE THREAD

**Issue by matthewbrahms** [flux-web/flux-web#11]
Hello, using helm to deploy is not an option currently for me.  I have used the `helm template` tool to try to render out the `.yaml` files.  I have done so and deployed and I get the frontpage to load, but no workloads or namespaces are loading.  I also see no logs in the frontend pod container except the following:
```
flux-web-frontend > frontend-nuxt@2.9.1 start /app
flux-web-frontend > nuxt-ts start --hostname $APP_HOST --port $APP_PORT
flux-web-frontend 
flux-web-frontend ℹ Listening on: http://100.123.199.93:8080/
flux-web-frontend 
flux-web-frontend  WARN  'state' should be a method that returns an object in store/workloads/index.ts
flux-web-frontend 
flux-web-frontend 
flux-web-frontend  WARN  'state' should be a method that returns an object in store/namespaces/index.ts
```

I am wondering if I could get an explanation or have someone point me in the right direction to find documentation for the following environment variables that are set in the `flux-web-frontend` container:
```
env:
- name: APP_HOST
  value: '0.0.0.0'
- name: APP_PORT
  value: '8080'
- name: NODE_ENV
  value: production
- name: READ_ONLY
  value: "true"
- name: "API_EXTERNAL_URL"
  value: "//flux-web.local/api/v1"
- name: "BASE_URL"
  value: "//flux-web.local"
- name: "WS_URL"
  value: "flux-web.local/ws/v1"
```
For instance, with the URL's, if I am using a custom domain/dns, should I set that to be the custom domain?

I suspect it is something here that I have incorrectly configured.

I am deploying it in Kubernetes and I do have ingress working, etc.  Also, I am seeing in the logs the `200`'s for the backend -> frontend healthcheck. :)

If I can get an explanation, I would be happy to help contribute back to documenting it!

Thanks!
Matthew
